# Set the project language
language: c

# Set test platforms
os:
  - osx
  - linux

# Enable use of container-based infrastructure for Linux
sudo: false

# Configuration
env:
  global:
    - LIBUV_VERSION=1.7.4
  matrix:
    - CMAKE_BUILD_TYPE=Debug
    - CMAKE_BUILD_TYPE=Release

# Upgrade CMake since Travis CI uses Ubuntu 12.04 with CMake 2.8.7
addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

# Run the build and the test
script:
  - ./posix-ci.sh

# Send notifications
notifications:
  email:
    - jacob@havoc.io
