# Versioning
version: 1.7.0.{build}

# Configuration
environment:
  LIBUV_VERSION: 1.7.0
  matrix:
    - CMAKE_BUILD_TYPE: Debug
    - CMAKE_BUILD_TYPE: Release

# Set up clone path (this is the default, but just to make it explicit)
clone_folder: c:\projects\libuv-cmake

# Download libuv, run CMake, and build
build_script:
  - cd c:\projects\libuv-cmake
  - git clone https://github.com/libuv/libuv.git
  - cd libuv
  - git checkout -q v%LIBUV_VERSION%
  - cd ..
  - copy CMakeLists.txt libuv
  - mkdir build
  - cd build
  - cmake -G"Visual Studio 11" ..\libuv
  - cmake --build . --config %CMAKE_BUILD_TYPE%

# Run tests
# NOTE: Currently intentionally disabled, see note in README.md
# NOTE: Must be done inside build directory because that's where test fixtures
# are copied
# HACK: Use 'call ...' to invoke the test runner because AppVeyor can't parse a
# command starting with %
# test_script:
#   - cd c:\projects\libuv-cmake\build
#   - call %CMAKE_BUILD_TYPE%\run-tests.exe

# Send notifications
notifications:
  - provider: Email
    to:
      - jacob@havoc.io
